name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      run: dotnet restore HorsesForCourses.sln

    - name: Build solution
      run: dotnet build HorsesForCourses.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test HorsesForCourses.Tests/HorsesForCourses.Tests.csproj --no-build --configuration Release --logger trx
